---
title: '5'
author: "Jiang"
date: "2021/11/10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 5

### 5.2
```{r, echo=TRUE}
set.seed(0)
sample_X_015 <- function(a,b,n){
  sample_X<-data.frame(U=runif(n))%>%
    mutate(X=case_when(
      (0<=U)&(U<a)~1,
      (a<=U)&(U<a+b)~5,
      (a+b<=U)&(U<=1)~0))%>%
    pull(X)
  return(sample_X)
}

mean(sample_X_015(0.5,0.1,10000))
var(sample_X_015(0.5,0.1,10000))

simulation_by_data<-data.frame(beta=seq(0,0.9,0.01))%>%
  mutate(sample_X=map(.x=beta,~sample_X_015(0.1,.x,100)))%>%
  mutate(sample_avg=map_dbl(.x=sample_X,~mean(.x)))%>%
  select(-sample_X)%>%
  mutate(expectation=0.1+5*beta)
simulation_by_data%>%rename(Sample=sample_avg,Expectation=expectation)

linetypes <- c("Expectation"="solid","sample"="dashed")
plot<-ggplot(data=simulation_by_data)+geom_line(aes(x=beta,y=expectation,linetype="Expectation"))+theme_bw()+geom_point(aes(x=beta,y=sample_avg,linetype="sample"))+scale_linetype_manual(values=linetypes)
plot


```

```{r, echo=TRUE}
x<-seq(-4,6,0.1)
normal_densities_by_x<-data.frame(x=x,density=dnorm(x,mean=1,sd=sqrt(1)),var=1)%>%
  rbind(data.frame(x=x,density=dnorm(x,mean=1,sd=sqrt(2)),var=2))%>%
  rbind(data.frame(x=x,density=dnorm(x,mean=1,sd=sqrt(3)),var=3))
ggplot(normal_densities_by_x,aes(x,y=density,color=as.character(var),
linetype=as.character(var)))+geom_line()+
  theme_bw()+labs(color="Variance",linetype="Variance",x="x",y="Density")

```

```{r,echo=TRUE}
set.seed(0)
standardGaussianSample <- rnorm(100)
mean1Var3GaussianSampleA <- 1+sqrt(3)*standardGaussianSample

set.seed(0)
mean1Var3GaussianSampleB<-rnorm(100,1,sqrt(3))
all.equal(mean1Var3GaussianSampleA,mean1Var3GaussianSampleB)

colors<-c("Population density"="red", "Sample kernel density"="blue",
"Population mean"="green", "Sample mean"="violet")
linetypes<-c("Population density"="solid", "Sample kernel density"="dashed",
"Population mean"="solid", "Sample mean"="dashed")
ggplot()+labs(x="x",y="Density")+theme_bw()+
geom_line(data=(normal_densities_by_x%>%
filter(var==3)),
aes(x,y=density,color="Population density"))+
# create plot of theoretical density
geom_density(data=data.frame(x=mean1Var3GaussianSampleA),
aes(x=x,color="Sample kernel density",
linetype="Sample kernel density"))+
# add in kernel density plot from real sample
geom_vline(aes(xintercept=1,color="Population mean",
linetype="Population mean"))+
geom_vline(aes(xintercept=mean(mean1Var3GaussianSampleA),
color="Sample mean",linetype="Sample mean"))+
scale_color_manual(name = "Legend", values=colors)+
scale_linetype_manual(name="Legend", values=linetypes)

```

```{r,echo=TRUE}
p<-0.7
n<-50
binom_df<-data.frame(x=seq(0,n))%>%
mutate(pmf=map_dbl(.x=x,~dbinom(x=.x,size=n,prob=p)))
binom_df%>%
head(3)

inc<-0.01
mu=n*p
sigma=sqrt(n*p*(1-p))
gaussian_df<-data.frame(x=seq(0,n,inc))%>%
mutate(pdf=map_dbl(.x=x,~dnorm(x=.x,mean=mu,sd=sigma)))
gaussian_df%>%head(3)

colors<-c("Gaussian pdf"="red", "Binomial pmf"="blue")
fill<-c("Gaussian pdf"="white", "Binomial pmf"="white")
ggplot()+labs(x="x",y="Probability")+theme_bw()+
geom_line(data=gaussian_df,
aes(x,y=pdf,color="Gaussian pdf"),size=2)+
# create plot of Gaussian density
geom_col(data=binom_df,
aes(x=x,y=pmf,color="Binomial pmf",fill="Binomial pmf"))+
scale_color_manual(name = "", values=colors)+
scale_fill_manual(name = "", values=fill)+
xlim(c(20,50))
```
